### PR TITLE
fix: missing OS namespace for MSVC compiler code

### PR DESCRIPTION
**Pull request by rodolforg**
Broken since 07897538bc847153e48f525e7aefeaa4bea11fe4 (included in #2710)

Also, it now uses wide string for folder path.

### CODE REVIEW

**Comment by ice0** [comment]
Currently it fails with the error:
```
C:\projects\synfig\synfig-core\src\synfig\main.cpp(237,25): error C2440: 'initializing': cannot convert from
 'synfig::filesystem::Path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' [C:\projects\build\synfig-core\src\synfig\libsynfig.vcxproj]
```

So I think there should be something like?
```
String module_location = synfig::OS::get_binary_path("").u8_str();
```

**Comment by rodolforg** [comment]
Ugh.

Fixed it. It was an old commit I had here. And now I fixed the missing wide string for fontconfig path - I hope.

**Comment by ice0** [comment]
Now it stops with error:
```
C:\projects\synfig\synfig-core\src\synfig\main.cpp(238,58): error C2660: 'synfig::OS::get_binary_path': function does not take 0 arguments [C:\projects\build\synfig-core\src\synfig\libsynfig.vcxproj]
```

**Comment by rodolforg** [comment]
Funny.
Current master uses zero argument:
https://github.com/synfig/synfig/blob/master/synfig-core/src/synfig/os.h#L224-L228

**Comment by ice0** [comment]
> Funny. Current master uses zero argument: https://github.com/synfig/synfig/blob/master/synfig-core/src/synfig/os.h#L224-L228

Looks like I forgot to rebase my branch when testing. Currently it's rebuilding, so I'll be able to check that out later.

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!
