### PR TITLE
Implement zooming with pen

### PR DESCRIPTION
**Pull request by bobbybee**
This handles a subset of #421 

In particular, it does not implement rotation, since there is no canvas rotation implemented as it is (?). If/when that is changed, the stubs are here.

It also requires the pen button as opposed to the space bar, mimicking the existing pan keybinding. Fixing this (with a configuration option) would be somewhat more involved. It would require some refactoring. It would also conflict with #414 as noted. Perhaps that should be a separate patchset?

### CODE REVIEW

**Comment by bobbybee** [comment]
(Found a bug, don't merge)

**Comment by bobbybee** [comment]
OK. This should match Krita's algorithm.

**Comment by morevnaproject** [comment]
> there is no canvas rotation implemented as it is (?)

Yes, there are no canvas rotation implemented.

Tested the fix - works perfectly for me. Will merge it right away. Thank you! ^__^

**Comment by morevnaproject** [comment]
Now shipped with Synfig 1.3.5 - https://morevnaproject.org/2017/12/25/synfig-studio-1-3-5/

**Comment by bobbybee** [comment]
Hooray! :)
