### ISSUE TITLE
Can't build on OSX 10.9:  variable length array of non-POD element type

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#697]
**Synfig version & platform**:
master branch (commit 1d1ab7f883ffe290c944d0bbb3219c0aed56403d)

**Issue description**:
Tried to build master branch (commit 1d1ab7f883ffe290c944d0bbb3219c0aed56403d) on OSX 10.9. Got an error:
```
/Users/admin/sources/synfig/synfig-core/src/synfig/rendering/software/task/tasktransformationaffinesw.cpp:355:26: error: variable length array of non-POD element type 'synfig::rendering::TaskTransformationAffineSW::Helper::Generic<&synfig::rendering::software::PackedSurface::Reader::reader, &synfig::rendering::software::PackedSurface::Reader::reader_cook>::MapPixelFull'
                        MapPixelFull full_cols[sw], *full_cols_begin = full_cols, *full_cols_end = full_cols_begin;
                                              ^
```

**Comment by morevnaproject** [comment]
Fixed by @blackwarthog via 3e8f8e2d23d5c565ab7c76640afbb95ea35ce6ad
