### PR TITLE
[Release] v1.4.1

### PR DESCRIPTION
**Pull request by ice0**
============== 2021.04.20 ======================
- Improved dialog waypoint UX (#1182)
- Change order of Waypoint Editor buttons to match other dialogs (#1880) 
- [Synfig Studio] Waypoint Editor didn't properly support enums (#1968)
- [Synfig Studio] fix mainwindow not showing when is offscreen (#1973)
-  [Synfig Studio] Bumped year in About dialog (#1977) 

============== 2021.02.28 ======================
- [Synfig Studio] Fixed crash when inner layer duplicated twice #2050
- [Synfig Studio] Fix action LayerDuplicate with layers "duplicate" o.O #1971
- [Synfig Studio] fix "Link to Spline" showing when a vertex of spline itself is selected #1988
- [Synfig Studio] exception-guard now lists SynfigApp exception too #2028
- [Core] assure uniqueness for new node guid #2029
- [Synfig Studio] avoid dereference of invalid TreeIter on Layer TreeView #2043
- [ETL] current_working_directory() function now works correctly with non-Latin filenames #2011
- [Synfig Studio/Windows] Fixed issue with rendering to file when using non-Latin filenames #1940
- [Core] Added support for loading `average` values #1955

============================================

- [Synfig Studio] Fixed crash when frame rendering throws exception while animating #1861
- [Synfig Studio] Fixed incorrect import of `lst` files when path contains non-Latin characters #1924
- [Synfig Studio] Fixed crash when right-clicking on group in the Sets panel #1920
- [Synfig Studio/Windows] Fixed non-working command "Edit image in external tool..." #1912
- [Synfig Studio/Windows] Fixed load/save operations for Palette editor #1889
- [Synfig Studio/Windows] Fixed problem when plugins are failed to execute for files with non-Latin characters #1882
- Fixed crash in Spline Tangent converter #1836
- [MacOS] Fixed SynfigStudio.app won't start if renamed #1834
- Fixed error when output to MPEG-1 format with audio #1830
- Fixed animation interpolation for boolean values #1826
- Fixed Duplicate layer ignoring all layers but the first one #1829
- Restore Ctrl-c Ctrl+v ctrl+a in Color and Gradient Dialogs #1821
- Fixed crash in Spline Vertex converter #1802
- Autotools: make module flags and libs for the module itself only #1688
- Dialog windows now return true only if button with id=1 (accept) is clicked #1573
- Fixed crash on unsuccessful action with a clean history #1643
- Export video files with sound #1623
- Toolbar menu #1386
- Year is fixed in About dialog #1238

### CODE REVIEW

**Comment by morevnaproject** [comment]
I have submitted job to build server to generate test packages...

**Comment by morevnaproject** [comment]
@ice0 I have made attempt to build this PR on OSX 10.9 and it failed with the following error:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I../.. -I/Users/admin/sources/synfig/synfig-core/src -I/usr/local/opt/gettext/include -I/usr/local/include -I/usr/local/Cellar/glibmm/2.54.1/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.54.1/lib/glibmm-2.4/include -I/usr/local/Cellar/glib/2.54.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include -D_REENTRANT -I/usr/local/Cellar/glibmm/2.54.1/include/giomm-2.4 -I/usr/local/Cellar/glibmm/2.54.1/lib/giomm-2.4/include -I/usr/local/Cellar/glibmm/2.54.1/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.54.1/lib/glibmm-2.4/include -I/usr/local/Cellar/glib/2.54.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include -I/usr/local/Cellar/libxml++/2.40.1/include/libxml++-2.6 -I/usr/local/Cellar/libxml++/2.40.1/lib/libxml++-2.6/include -I/usr/local/Cellar/glibmm/2.54.1/include/glibmm-2.4 -I/usr/local/Cellar/glibmm/2.54.1/lib/glibmm-2.4/include -I/usr/local/Cellar/glib/2.54.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include -I/usr/include/libxml2 -I/usr/local/Cellar/cairo/1.14.12/include/cairo -I/usr/local/Cellar/glib/2.54.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.12.6/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/fftw/3.3.6-pl2/include -D_REENTRANT -I/usr/local/Cellar/mlt/6.4.1/include -I/usr/local/Cellar/mlt/6.4.1/include/mlt++ -I/usr/local/Cellar/mlt/6.4.1/include -I/usr/local/Cellar/mlt/6.4.1/include/mlt -I/Users/admin/sources/synfig/ETL -I/Users/admin/sources/synfig/_production/build/include/ETL -I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0 -I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include -DSYNFIG_NO_DEPRECATED -DLOCALEDIR=\"/Users/admin/sources/synfig/_production/build/share/locale\" -DLIBDIR=\"/Users/admin/sources/synfig/_production/build/lib\" -DSYSCONFDIR=\"/Users/admin/sources/synfig/_production/build/etc\" -fdiagnostics-color=always -std=c++11 -O2 -DNDEBUG -W -Wall -MT libsynfig_la-type.lo -MD -MP -MF .deps/libsynfig_la-type.Tpo -c /Users/admin/sources/synfig/synfig-core/src/synfig/type.cpp  -fno-common -DPIC -o .libs/libsynfig_la-type.o
In file included from /Users/admin/sources/synfig/synfig-core/src/synfig/type.cpp:32:
In file included from /Users/admin/sources/synfig/synfig-core/src/synfig/type.h:59:
In file included from /Users/admin/sources/synfig/ETL/ETL/handle:33:
/Users/admin/sources/synfig/ETL/ETL/_handle.h:37:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 error generated.
make: *** [libsynfig_la-type.lo] Error 1
```

**Comment by morevnaproject** [comment]
Ugh... maybe this is because I have set `export MACOSX_DEPLOYMENT_TARGET=10.5` environment variable...

**Comment by ice0** [comment]
> Ugh... maybe this is because I have set `export MACOSX_DEPLOYMENT_TARGET=10.5` environment variable...

10.5 was released in 2007, so no C++11 features. Can you try with 10.6?

**Comment by morevnaproject** [comment]
It worked with `MACOSX_DEPLOYMENT_TARGET=10.9` ^__^

**Comment by rodolforg** [comment]
Strange macOS error. It looks like g++ wasn't set as c++11 standard

**Comment by rodolforg** [comment]
Will any other commit pushed to 1.4.1?

**Comment by ice0** [comment]
> Will any other commit pushed to 1.4.1?

Yes. There are a few commits that only exist on this branch.

**Comment by rodolforg** [comment]
Nice!

 What about the remaining PR marked as backport ? Will still be available to 1.4.1?

**Comment by ice0** [comment]
> What about the remaining PR marked as backport ? Will still be available to 1.4.1?

Yes. I plan to merge them.

You can check progress here: https://github.com/synfig/synfig/projects/7

**Comment by rodolforg** [comment]
May I help you somehow?
By making Pull Requests to your ice0:v1.4.1 branch, for example?

**Comment by ice0** [comment]
> By making Pull Requests to your ice0:v1.4.1 branch, for example?

Sure. This will help a lot. 
Also, I think you can commit directly to this branch.

**Comment by rodolforg** [comment]
Missing merged PR labeled as Backport:
#1845 #1968 #1973 #1982 #1977  #1979 #1992 #1995 #1809 #2000 #2033 #2059 #2066 #2071 #2084 #2092 #2102

Missing open PR labeled as Backport:
#1935 #2086

**Comment by rodolforg** [comment]
Should we merge the Text Layer and Family Font Widget too?

**Comment by rodolforg** [comment]
@morevnaproject  @ice0  should we pick PR "single click for edit parameters of any type" ? #1337

**Comment by rodolforg** [comment]
From the 15 already merged PR, 7 can be picked normally:  #1973 #1977 #1982 #2000 #2071 #2084 #2092.

I guess #1845 ice0 ported indirectly.

#1968 depends on #1182 and #1880 : Waypoint Dialog improvements: button order, hide TCB parameters when not used, show enum values properly.

#1979 depends on #1337 #1429 #1963 (partially). Benefits: speed up layer tree movements and Single-click to edit value on Parameter Panel.

#1992 depends on #1514

**Comment by rodolforg** [comment]
I accidentally saw some Warp layer-related commits aren't in stable. Is it intentional?
cf1df92b252699989e3c36ce4406259a1e40ddd3
(and its predecessors 61ff9b8d620a045ad454fb55125dc69880c2b317 3ae388d8789484ffdb0c14dd6785d4fbece682cf f44ff0a64636419ff9d9e223ca355319fd0388e7 34a6856a6784c0f0959c64c173e0edf55fb15d7f )

**Comment by rodolforg** [comment]
I vote to include #1173  too XD

**Comment by rodolforg** [comment]
[Here](https://github.com/rodolforg/synfig/tree/ice0-v1.4.1) I merged all PR I cited except:
#1845 
#1992 (#1514)
#1997 

So, these were merged:
(#1182 #1880) #1968 #1973 #1977 (partial #1963 ) (#1429 #1337 #1351) #1979 #1982 #1995 #2000 #2033 #2059 (#2046 #2001 #2057) #2066 #2071 #2084 #2092 #2102 #1929 #2107 #2109

---

I proposed #1173 , the commits related to Widget_FontFamily implementation and Text Layer (fontconfig).

---

I don't know if we should update the Warp Layer (that was renamed to Perspective)
I don't know if #1853 helps on stable branch.

---

PR that aren't merged on master: #1935 #2086

**Comment by ice0** [comment]
> Should we merge the Text Layer and Family Font Widget too?

It's up to you. 
But as for me - I think it is better to backport only critical fixes and move forward with a new release. 
Each backported feature must be tested and documented in the changelog, which will increase the time it takes to release the fix.

**Comment by rodolforg** [comment]
> Each backported feature must be tested and documented in the changelog, which will increase the time it takes to release the fix.

Indeed. And I feel it's taking too long for my 'anxiety' :D

**Comment by morevnaproject** [comment]
> Indeed. And I feel it's taking too long for my 'anxiety' :D

Apologies for that! There is a messy segment around the point where "stable" branch divorced from "master" - at this time we were used to commit directly to master (without PRs) and this makes hard to track items for ChangeLog. It took time to sort out this mess. ^__^"

> I think it is better to backport only critical fixes and move forward with a new release.

I also agree with that.

> Should we merge the Text Layer and Family Font Widget too?

In the past I have made an attempt to do that, but we have hit problems with fontconfig version shipped in Appimage. So, this will require some additional work and tests.

I am proposing the following plan:

- Merge current PR into 1.4.x branch and release 1.4.1 ASAP (I think we are ready for that).
- After that merge [the branch](https://github.com/rodolforg/synfig/tree/ice0-v1.4.1) made by @rodolforg and release it as 1.4.2 (I expect it to be merged into 1.4.x  through separate PR).
- After that I would like to merge into 1.4.x all features from master branch up to this commit - 70c851e9028527208109f7cb49a90576f068d616. This includes reworked Warp Layer, New timetrack. This is expected to become 1.4.3. At this point we will pass the messy segment when we used to commit into master without PRs, and after that it will be easier to generate ChangeLogs and do releases faster.
- Finally, after that we can concentrate on preparing release of 1.5.0.

How about this? ^__^

**Comment by rodolforg** [comment]
> Merge current PR into 1.4.x branch and release 1.4.1 ASAP (I think we are ready for that).

Great! :)



>     * After that merge [the branch](https://github.com/rodolforg/synfig/tree/ice0-v1.4.1) made by @rodolforg and release it as 1.4.2 (I expect it to be merged into 1.4.x  through separate PR).

I suggest to merge at least (#1182 #1880) #1968 #1973 #1977 before release.
1. It bumps the year to current one lol
2. Avoid the constant complaining about Synfig doesn't open anymore on Windows (it's quite often recently on forum and here)
3. And it follows the PR order lol

**Review by morevnaproject — APPROVED** [review]

**Comment by morevnaproject** [comment]
> I suggest to merge at least (#1182 #1880) #1968 #1973 #1977 before release.
> 
>     1. It bumps the year to current one lol
> 
>     2. Avoid the constant complaining about Synfig doesn't open anymore on Windows (it's happening quite often recently on forum and here)
> 
>     3. And it follows the PR order lol

Added to this PR. Thank you! ^__^
