### ISSUE TITLE
MinGW cross-compilation fails after #2744

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2766]
PR #2744 makes impossible to cross-compile for WIndows using MinGW, it gives this error:

```
../../src/brushlib/brush.hpp: In member function 'void brushlib::Brush::update_states_and_setting_values(float, float, float, float, float, float)':
../../src/brushlib/brush.hpp:251:105: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  251 | (states[STATE_DIRECTION_DY], states[STATE_DIRECTION_DX])/(2*M_PI)*360 + 180.0, 180.0);
      |                                                             ^~~~
      |                                                             G_PI
../../src/brushlib/brush.hpp: In member function 'float brushlib::Brush::count_dabs_to(float, float, float, float)':
../../src/brushlib/brush.hpp:579:71: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  579 |   float angle_rad=states[STATE_ACTUAL_ELLIPTICAL_DAB_ANGLE]/360*2*M_PI;
      |                                                                   ^~~~
      |                                                                   G_PI
../../src/brushlib/brush.hpp: In member function 'bool brushlib::Brush::stroke_to(brushlib::Surface*, float, float, float, float, float, double)':
../../src/brushlib/brush.hpp:616:51: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  616 |       tilt_ascension = 180.0*atan2(-xtilt, ytilt)/M_PI;
      |                                                   ^~~~
      |                                                   G_PI
In file included from ../../src/synfigapp/canvasinterface.h:43,
                 from actions/layerpaint.cpp:38:
../../src/synfigapp/uimanager.h: In member function 'virtual synfigapp::UIInterface::Response synfigapp::DefaultUIInterface::yes_no_cancel(const string&, const string&, const string&, const string&, const string&, bool, synfigapp::UIInterface::Response)':
../../src/synfigapp/uimanager.h:97:9: warning: unused parameter 'hasDestructiveAction' [-Wunused-parameter]
   97 |    bool hasDestructiveAction,
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~
../../src/synfigapp/uimanager.h: In member function 'virtual synfigapp::UIInterface::Response synfigapp::ConfidentUIInterface::yes_no_cancel(const string&, const string&, const string&, const string&, const string&, bool, synfigapp::UIInterface::Response)':
../../src/synfigapp/uimanager.h:132:9: warning: unused parameter 'hasDestructiveAction' [-Wunused-parameter]
  132 |    bool hasDestructiveAction,
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from //build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from //build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/signal.h:8,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layer.h:39,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layers/layer_composite.h:34,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layers/layer_bitmap.h:34,
                 from actions/layerpaint.h:34,
                 from actions/layerpaint.cpp:37:
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of 'static void* (* sigc::internal::slot_call<T_functor, T_return>::address())(void*) [with T_functor = sigc::bound_mem_functor0<void, synfigapp::ValueDesc>; T_return = void; sigc::internal::hook = void* (*)(void*)]':
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h:2274:91:   required from 'sigc::slot<T_return(T_arg ...)>::slot(const T_functor&) [with T_functor = sigc::bound_mem_functor0<void, synfigapp::ValueDesc>; T_return = void; T_arg = {}]'
../../src/synfigapp/value_desc.h:134:121:   required from here
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h:468:14: warning: cast between incompatible function types from 'void (*)(sigc::internal::slot_rep*)' to 'sigc::internal::hook' {aka 'void* (*)(void*)'} [-Wcast-function-type]
  468 |     { return reinterpret_cast<hook>(&call_it); }
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:1805: actions/libsynfigapp_la-layerpaint.lo] Error 1
make[3]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio/src/synfigapp'
make[2]: *** [Makefile:450: all-recursive] Error 1
make[2]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio/src'
make[1]: *** [Makefile:693: all-recursive] Error 1
make[1]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio'
make: *** [Makefile:529: all] Error 2
```

Might be useful - https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier

Environment:
- Debian 11 bullseye
- gcc 10.2.1
- MingGW 10.2.1-6+24.2

**Comment by ice0** [comment]
I think the reason is an updated headers. You need to define `_USE_MATH_DEFINES`.

> _USE_MATH_DEFINES - <cmath> header need this define to add `M_PI` define

**Comment by morevnaproject** [comment]
Thank you!

I have made attempt to add `_USE_MATH_DEFINES` (https://github.com/synfig/synfig/commit/d50f85d4d026c48c55360c7178ddf825ff861d84), but the error still remains.

I guess this fix not working because we include `iostream` before `cmath`, as noted [here](https://stackoverflow.com/a/58379321).

**Comment by morevnaproject** [comment]
I have found a solution - https://github.com/synfig/synfig/commit/49504702f74b484f6f049ec87af9fa0efd08d106
Although, I do not like it.

I do not like it because adding line in one file (synfig-studio/src/synfigapp/actions/layerpaint.cpp) fixes compilation error in another file (synfig-studio/src/brushlib/brush.hpp).

**Comment by morevnaproject** [comment]
I would prefer to add something like this -
```
#ifndef M_PI
#define M_PI (3.14159265358979323846)
#endif
```

What do you think?

**Comment by ice0** [comment]
> I have made attempt to add `_USE_MATH_DEFINES` ([d50f85d](https://github.com/synfig/synfig/commit/d50f85d4d026c48c55360c7178ddf825ff861d84)), but the error still remains.
> 
> I guess this fix not working because we include `iostream` before `cmath`, as noted [here](https://stackoverflow.com/a/58379321).

I think the problem can be deeper.
I did an example and it compiles fine (with mingw compiler):

`x86_64-w64-mingw32-g++ --std=c++11 ./test.cpp`

```
#include <iostream>
#define _USE_MATH_DEFINES
#include <cmath>

int main() {
    std::cout << "PI: " << M_PI << std::endl;
    return 0;
}
```

**Comment by rodolforg** [comment]
Maybe we should update brushlib (libmypaint) or change the brush.hpp to not have code in this header file
