### ISSUE TITLE
Synfig-core fails to build libavcodec module with old FFmpeg, no video import feature

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#744]
System: Ubuntu 16.04

When trying to build synfig-core using "--with-libavcodec" option the compilation fails with an error:

```
/synfig/synfig-core/src/modules/mod_libavcodec/trgt_av.cpp:199:6: error: reference to ‘AVPixelFormat’ is ambiguous
synfig/synfig-core/src/modules/mod_libavcodec/trgt_av.cpp:209:53: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
```

Currently libavcodec module is disabled (see #742 and #743), but with this we also lost support for video import. This should be solved at high priority.

**Comment by morevnaproject** [comment]
The build works fine on newer systems (they have newer FFmpeg).

**Comment by morevnaproject** [comment]
Looks like build files if FFmpeg version is older than 3.0.

https://github.com/LibVNC/libvncserver/issues/231
https://github.com/gerbera/gerbera/issues/52#issuecomment-287712812

**Comment by morevnaproject** [comment]
As an alternative solution, we can set a hard requirement to compile with FFmpeg >= 3.0.

**Comment by rohitsanjay** [comment]
@morevnaproject  
It would be better if we upgrade FFmpeg during building.
If it would be successful then allow me to work on this.

**Comment by morevnaproject** [comment]
@rohitsanjay Do you mean to add an explicit check if we have FFmpeg >= 3.0?

**Comment by rohitsanjay** [comment]
@morevnaproject 
Yes, we can do explicit check too to verify the version of FFmpeg and we can edit the script file to upgrade FFmpeg.

**Comment by morevnaproject** [comment]
@rohitsanjay 
Let's add a verification for FFmpeg version >= 3.0. This would be enough.

> and we can edit the script file to upgrade FFmpeg.

I think this is not needed, because newer systems has correct version of FFmpeg.
What we can do is to provide instructions for users of Ubuntu 16.04 and 16.10 on how to install newer FFmpeg (and let them do that manually).

And, as  soon as we get #666 done, this issue will be resolved automatically (the correct version of FFmpeg will be provided by Conan package). ^__^

**Comment by rohitsanjay** [comment]
@morevnaproject 
Ok, I will do it and edit the building doc too.

**Comment by morevnaproject** [comment]
Great! ^__^

**Comment by morevnaproject** [comment]
Hi @rohitsanjay ! Do you plan to continue working on this?

**Comment by rohitsanjay** [comment]
@morevnaproject 
Since it was part of issue #666, I don't think I will be able to do this.

**Comment by morevnaproject** [comment]
Okay, thanks for letting me know!

**Comment by ice0** [comment]
Fixed in https://github.com/synfig/synfig/commit/8f89ca29ee724e59cce0271ef892272c9c68c7a0
