### PR TITLE
Don't crash if exception thrown while rendering WorkArea

### PR DESCRIPTION
**Pull request by rodolforg**
It is related to #231 . It doesn't crash anymore.

A Exported ValueNode duck, if selected, make Studio crash when user unexport the valuenode.
The duck stores a ValueDesc that refers to exported valuenode by its name. When unexported, there isn't a valuenode with that name anymore.

The perfect(?) solution would be to self'destroy' the duck if it detects its valuenode name (id) changed to empty string.

### CODE REVIEW

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by rodolforg** [comment]
@ice0 do you think it should be cherry-picked to v.1.3.x?

**Comment by ice0** [comment]
@rodolforg better to ask @morevnaproject :)
it requires #1475 to work.
#1475 added warning about unused `_exception_guard_error_code` variable. 
I also have a fix for MSVC for it (I will do PR this week)

**Comment by morevnaproject** [comment]
Let's try to include and see what happen. ^__^

**Comment by rodolforg** [comment]
@ice0 Oh, I thought that PR was pushed https://github.com/synfig/synfig/pull/1475#issuecomment-640516302
It seems it wasn't.

About the warnings, yeah I saw them now o.O How didn't I see them before? o.O

**Comment by morevnaproject** [comment]
I have included commits form #1475 and from this PR into 1.3.x. But Synfig fails to compile with the error:

```
g++ -DHAVE_CONFIG_H -I. -I/home/konstantin/sources/synfig-1.3.x/synfig-studio/src/gui -I../..  -I/home/konstantin/sources/synfig-1.3.x/synfig-studio/src  -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -pthread -D_REENTRANT -I/home/konstantin/sources/synfig-1.3.x/synfig-core/src -I/home/konstantin/sources/synfig-1.3.x/ETL -I/home/konstantin/sources/synfig-1.3.x/_production/build/include/ETL -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/OpenEXR -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIMAGE_DIR=\"/home/konstantin/sources/synfig-1.3.x/_production/build/share/pixmaps/synfigstudio\" -DIMAGE_EXT=\"png\" -DPLUGIN_DIR=\"/home/konstantin/sources/synfig-1.3.x/_production/build/share/synfig/plugins\" -DSOUND_DIR=\"/home/konstantin/sources/synfig-1.3.x/_production/build/share/synfig/sounds\" -DUI_DIR=\"/home/konstantin/sources/synfig-1.3.x/_production/build/share/synfig/ui\" -DLOCALEDIR=\"/home/konstantin/sources/synfig-1.3.x/_production/build//locale\" -fdiagnostics-color=always -O2 -DNDEBUG -MT dials/synfigstudio-zoomdial.o -MD -MP -MF dials/.deps/synfigstudio-zoomdial.Tpo -c -o dials/synfigstudio-zoomdial.o `test -f 'dials/zoomdial.cpp' || echo '/home/konstantin/sources/synfig-1.3.x/synfig-studio/src/gui/'`dials/zoomdial.cpp
In file included from /home/konstantin/sources/synfig-1.3.x/synfig-studio/src/gui/dials/zoomdial.cpp:43:0:
/home/konstantin/sources/synfig-1.3.x/synfig-studio/src/gui/dials/zoomdial.cpp: In member function ‘void studio::ZoomDial::after_event(GdkEvent*)’:
/home/konstantin/sources/synfig-1.3.x/synfig-studio/src/gui/exception_guard.h:33:17: error: ‘Exception’ in namespace ‘synfig’ does not name a type
   catch(synfig::Exception::Exception& x) \
                 ^
```

It seems last commit from this PR gives problems. Do I need to include some other commits from master branch to make it work in 1.3.x?

**Comment by morevnaproject** [comment]
I have pushed all commits except the last one to 1.3.x branch.

**Comment by rodolforg** [comment]
Did you rebuild synfig-core too?
I changed the exception.h

**Comment by morevnaproject** [comment]
@rodolforg Yes, I did full rebuild...

**Comment by morevnaproject** [comment]
Added ```#include <synfig/exception.h>``` to `synfig-studio/src/gui/exception_guard.h` and it works now! ^__^

screenshot_003

**Comment by morevnaproject** [comment]
Committed changes. Please check if everything alright here - https://github.com/synfig/synfig/commits/v1.3.x

**Comment by rodolforg** [comment]
> Added `#include <synfig/exception.h>` to `synfig-studio/src/gui/exception_guard.h` and it works now! ^__^
> 
> screenshot_003

Oh, sorry. I missed it. :/ Funny it built successfully master branch

**Comment by rodolforg** [comment]
> Committed changes. Please check if everything alright here - https://github.com/synfig/synfig/commits/v1.3.x

It seem it is :D

**Comment by morevnaproject** [comment]
Yes, just to make sure I have tested #231 in branch 1.3.x (before and after the fix). I can confirm the issue is gone. Thank you! ^__^
