### PR TITLE
fix: build on Ubuntu 16.04

### LINKED ISSUE #2964: Cannot build on Ubuntu 16.04
**Describe the bug**
Following instructions from docs

**To Reproduce**
1. Clone the Synfig repo as stated in [docs](https://synfig-docs-dev.readthedocs.io/en/latest/building/Preparing%20Environment.html)
2. Execute ./1-setup-linux-native.sh
3. Execute ./2-build-debug.sh
4. Gives error

```
In file included from /usr/include/sigc++-2.0/sigc++/signal_base.h:27:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from /usr/include/glibmm-2.4/glibmm/signalproxy.h:12,
                 from /usr/include/glibmm-2.4/glibmm/objectbase.h:23,
                 from /usr/include/glibmm-2.4/glibmm/wrap.h:23,
                 from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:26,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:23,
                 from /usr/include/glibmm-2.4/glibmm/miscutils.h:25,
                 from /home/veer/synfig.git/ETL/ETL/_stringf.h:45,
                 from /home/veer/synfig.git/ETL/ETL/stringf:34,
                 from /home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:41:
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘class sigc::slot0<bool(synfig::Node*)>’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1655:7:   required from ‘class sigc::slot<bool(synfig::Node*)>’
/home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:1544:39:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:431:42: error: function returning a function
   typedef T_return (*call_type)(rep_type*);
                                          ^
/usr/include/sigc++-2.0/sigc++/functors/slot.h:437:19: error: function returning a function
   inline T_return operator()() const
                   ^
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘class sigc::slot0<bool(const synfig::Node*)>’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1655:7:   required from ‘class sigc::slot<bool(const synfig::Node*)>’
/home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:1544:39:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:431:42: error: function returning a function
   typedef T_return (*call_type)(rep_type*);
                                          ^
/usr/include/sigc++-2.0/sigc++/functors/slot.h:437:19: error: function returning a function
   inline T_return operator()() const
                   ^
In file included from /usr/include/sigc++-2.0/sigc++/signal_base.h:27:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:8,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from /usr/include/glibmm-2.4/glibmm/signalproxy.h:12,
                 from /usr/include/glibmm-2.4/glibmm/objectbase.h:23,
                 from /usr/include/glibmm-2.4/glibmm/wrap.h:23,
                 from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:26,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:23,
                 from /usr/include/glibmm-2.4/glibmm/miscutils.h:25,
                 from /home/veer/synfig.git/ETL/ETL/_stringf.h:45,
                 from /home/veer/synfig.git/ETL/ETL/stringf:34,
                 from /home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:41:
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘struct sigc::internal::slot_call0<synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>::<lambda(synfig::Node*)>, bool(synfig::Node*)>’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:454:82:   required from ‘sigc::slot0<T_return>::slot0(const T_functor&) [with T_functor = synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1668:26:   required from ‘sigc::slot<T_return, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:1544:39:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:104:19: error: function returning a function
   static T_return call_it(slot_rep* rep)
                   ^
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘struct sigc::internal::slot_call0<synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>, bool(synfig::Node*)>’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:454:82:   required from ‘sigc::slot0<T_return>::slot0(const T_functor&) [with T_functor = synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1668:26:   required from ‘sigc::slot<T_return, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = synfig::Canvas::invoke_signal_value_node_child_removed(etl::handle<synfig::ValueNode>, etl::handle<synfig::ValueNode>)::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:1552:54:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:104:19: error: function returning a function
/usr/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of ‘struct sigc::internal::slot_call0<synfig::Node::find_all_parents_of_type() const [with T = synfig::Layer_PasteCanvas]::<lambda(synfig::Node*)>, bool(synfig::Node*)>’:
/usr/include/sigc++-2.0/sigc++/functors/slot.h:454:82:   required from ‘sigc::slot0<T_return>::slot0(const T_functor&) [with T_functor = synfig::Node::find_all_parents_of_type() const [with T = synfig::Layer_PasteCanvas]::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/usr/include/sigc++-2.0/sigc++/functors/slot.h:1668:26:   required from ‘sigc::slot<T_return, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>::slot(const T_functor&) [with T_functor = synfig::Node::find_all_parents_of_type() const [with T = synfig::Layer_PasteCanvas]::<lambda(synfig::Node*)>; T_return = bool(synfig::Node*)]’
/home/veer/synfig.git/synfig-core/src/synfig/node.h:282:3:   required from ‘std::vector<etl::handle<T> > synfig::Node::find_all_parents_of_type() const [with T = synfig::Layer_PasteCanvas]’
/home/veer/synfig.git/synfig-core/src/synfig/canvas.cpp:121:103:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:104:19: error: function returning a function
  CXX      libsynfig_la-loadcanvas.lo
  CXX      libsynfig_la-main.lo
Makefile:2697: recipe for target 'libsynfig_la-canvas.lo' failed
make[3]: *** [libsynfig_la-canvas.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:53:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:224:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<_xmlSAXHandler> sax_handler_;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:54:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/parsers/textreader.h:260:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<PropertyReader> propertyreader;
          ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:69:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/relaxngschema.h:108:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Impl> pimpl_;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:70:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/xsdschema.h:99:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Impl> pimpl_;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:73:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/validators/relaxngvalidator.h:159:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Impl> pimpl_;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:75:0,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/libxml++-2.6/libxml++/validators/xsdvalidator.h:149:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Impl> pimpl_;
        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:14,
                 from /usr/include/libxml++-2.6/libxml++/libxml++.h:53,
                 from /home/veer/synfig.git/synfig-core/src/synfig/loadcanvas.cpp:49:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
make[3]: Leaving directory '/home/veer/synfig.git/_debug/synfig-core/src/synfig'
Makefile:465: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/veer/synfig.git/_debug/synfig-core/src'
Makefile:687: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/veer/synfig.git/_debug/synfig-core'
Makefile:555: recipe for target 'all' failed
make: *** [all] Error 2
```

**System information:**
 - OS: Ubuntu
 - OS version: 16.04
 - Commit ID: 80aabd4

### PR DESCRIPTION
**Pull request by ice0**
Fix #2964

Details about crash on Ubuntu 16.04:

```
gdb --args /root/projects/build/output/Debug/bin/synfig about_icon.sif -o root/projects/build/output/Debug/share/synfig/icons/classic/128x128/about_icon.png --time 0f
```

```
Thread 1 "synfig" received signal SIGSEGV, Segmentation fault.
0x00007f9a608883f0 in ?? ()
(gdb) bt
#0  0x00007f9a608883f0 in ?? ()
#1  0x00007f9a63db3719 in mlt_property_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#2  0x00007f9a63db5860 in mlt_properties_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#3  0x00007f9a63dc6811 in mlt_factory_close () from /usr/lib/x86_64-linux-gnu/libmlt.so.6
#4  0x00007f9a67f38e73 in synfig::SoundProcessor::subsys_stop () at /root/projects/synfig/synfig-core/src/synfig/soundprocessor.cpp:296
#5  0x00007f9a67e7207b in synfig::Main::~Main (this=0x7ffe962eec80, __in_chrg=<optimized out>) at /root/projects/synfig/synfig-core/src/synfig/main.cpp:434
#6  0x0000000000440467 in main (argc=6, argv=0x7ffe962ef638) at /root/projects/synfig/synfig-core/src/tool/main.cpp:272
```

This looks like a double-free issue.

I checked MLT example, and commented-out delete.
https://github.com/mltframework/mlt/blob/master/src/examples/play.cpp

### CODE REVIEW

File: synfig-core/src/synfig/node.h [hunk 1]
```diff
@@ -264,8 +264,8 @@ class Node : public etl::rshared_object
 
 	//! Callback function for a foreach method.
 	//! If it returns true, the foreach iteration is halted.
-	using ForeachFunc = sigc::slot<bool(Node*)>;
-	using ConstForeachFunc = sigc::slot<bool(const Node*)>;
+	using ForeachFunc = sigc::slot1<bool, Node*>;
+	using ConstForeachFunc = sigc::slot1<bool, const Node*>;
```
Comment (rodolforg) [inline synfig-core/src/synfig/node.h:268]: Doesn't accept the `bool(Node*)` notation? :(

Anyway, does it need the explicit `1` in `sigc::slot`?

File: synfig-core/src/synfig/soundprocessor.cpp [hunk 2]
```diff
@@ -292,7 +292,8 @@ bool SoundProcessor::subsys_init() {
 bool SoundProcessor::subsys_stop()
 {
 #ifndef WITHOUT_MLT
-	delete Internal::repository;
+	// delete leads to crush on Ubuntu 16.04
```
Comment (rodolforg) [inline synfig-core/src/synfig/soundprocessor.cpp:295]: typo: "crash"

File: synfig-studio/src/gui/dials/jackdial.h [hunk 3]
```diff
@@ -55,7 +55,7 @@ class JackDial : public Gtk::Box
 public:
 	JackDial();
 	void set_state(bool enabled);
-	Glib::SignalProxy<void> signal_toggle_jack() { return toggle_jack_button->signal_toggled(); }
+	Glib::SignalProxy0<void> signal_toggle_jack() { return toggle_jack_button->signal_toggled(); }
```
Comment (rodolforg) [inline synfig-studio/src/gui/dials/jackdial.h:58]: Is `0` really needed?

File: synfig-core/src/synfig/node.h (hunk 1 above)
Comment (ice0) [reply synfig-core/src/synfig/node.h:268]: Yes. For some reason gcc5 in Ubuntu 16.04 fails to compile it with the error:
```
/usr/include/sigc++-2.0/sigc++/functors/slot.h:104:19: error: function returning a function
```

Looks like it can't correct parse template with `()` in it like here: `sigc::slot<bool(Node*)>;`, so switching to this template allows us to skip this.

**Review by rodolforg — DISMISSED** [review]
It fixes Debian 8 also :)

File: synfig-core/src/synfig/node.h (hunk 1 above)
Comment (rodolforg) [reply synfig-core/src/synfig/node.h:268]: OK

File: synfig-core/src/synfig/soundprocessor.cpp (hunk 2 above)
Comment (ice0) [reply synfig-core/src/synfig/soundprocessor.cpp]: Sure. Done.

**Review by rodolforg — APPROVED** [review]
