### PR TITLE
fix: Fix cross-compilation with MinGW on Debian 11

### LINKED ISSUE #2766: MinGW cross-compilation fails after #2744
PR #2744 makes impossible to cross-compile for WIndows using MinGW, it gives this error:

```
../../src/brushlib/brush.hpp: In member function 'void brushlib::Brush::update_states_and_setting_values(float, float, float, float, float, float)':
../../src/brushlib/brush.hpp:251:105: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  251 | (states[STATE_DIRECTION_DY], states[STATE_DIRECTION_DX])/(2*M_PI)*360 + 180.0, 180.0);
      |                                                             ^~~~
      |                                                             G_PI
../../src/brushlib/brush.hpp: In member function 'float brushlib::Brush::count_dabs_to(float, float, float, float)':
../../src/brushlib/brush.hpp:579:71: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  579 |   float angle_rad=states[STATE_ACTUAL_ELLIPTICAL_DAB_ANGLE]/360*2*M_PI;
      |                                                                   ^~~~
      |                                                                   G_PI
../../src/brushlib/brush.hpp: In member function 'bool brushlib::Brush::stroke_to(brushlib::Surface*, float, float, float, float, float, double)':
../../src/brushlib/brush.hpp:616:51: error: 'M_PI' was not declared in this scope; did you mean 'G_PI'?
  616 |       tilt_ascension = 180.0*atan2(-xtilt, ytilt)/M_PI;
      |                                                   ^~~~
      |                                                   G_PI
In file included from ../../src/synfigapp/canvasinterface.h:43,
                 from actions/layerpaint.cpp:38:
../../src/synfigapp/uimanager.h: In member function 'virtual synfigapp::UIInterface::Response synfigapp::DefaultUIInterface::yes_no_cancel(const string&, const string&, const string&, const string&, const string&, bool, synfigapp::UIInterface::Response)':
../../src/synfigapp/uimanager.h:97:9: warning: unused parameter 'hasDestructiveAction' [-Wunused-parameter]
   97 |    bool hasDestructiveAction,
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~
../../src/synfigapp/uimanager.h: In member function 'virtual synfigapp::UIInterface::Response synfigapp::ConfidentUIInterface::yes_no_cancel(const string&, const string&, const string&, const string&, const string&, bool, synfigapp::UIInterface::Response)':
../../src/synfigapp/uimanager.h:132:9: warning: unused parameter 'hasDestructiveAction' [-Wunused-parameter]
  132 |    bool hasDestructiveAction,
      |    ~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from //build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/signal_base.h:27,
                 from //build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/signal.h:8,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layer.h:39,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layers/layer_composite.h:34,
                 from //build/packet/win-64/synfigcore-master/install/include/synfig-1.0/synfig/layers/layer_bitmap.h:34,
                 from actions/layerpaint.h:34,
                 from actions/layerpaint.cpp:37:
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h: In instantiation of 'static void* (* sigc::internal::slot_call<T_functor, T_return>::address())(void*) [with T_functor = sigc::bound_mem_functor0<void, synfigapp::ValueDesc>; T_return = void; sigc::internal::hook = void* (*)(void*)]':
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h:2274:91:   required from 'sigc::slot<T_return(T_arg ...)>::slot(const T_functor&) [with T_functor = sigc::bound_mem_functor0<void, synfigapp::ValueDesc>; T_return = void; T_arg = {}]'
../../src/synfigapp/value_desc.h:134:121:   required from here
//build/packet/win-64/sigcpp-2.10.0/install/include/sigc++-2.0/sigc++/functors/slot.h:468:14: warning: cast between incompatible function types from 'void (*)(sigc::internal::slot_rep*)' to 'sigc::internal::hook' {aka 'void* (*)(void*)'} [-Wcast-function-type]
  468 |     { return reinterpret_cast<hook>(&call_it); }
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:1805: actions/libsynfigapp_la-layerpaint.lo] Error 1
make[3]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio/src/synfigapp'
make[2]: *** [Makefile:450: all-recursive] Error 1
make[2]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio/src'
make[1]: *** [Makefile:693: all-recursive] Error 1
make[1]: Leaving directory '/build/packet/win-64/synfigstudio-master/build/synfig/synfig-studio'
make: *** [Makefile:529: all] Error 2
```

Might be useful - https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier

Environment:
- Debian 11 bullseye
- gcc 10.2.1
- MingGW 10.2.1-6+24.2

### PR DESCRIPTION
**Pull request by morevnaproject**
Closes #2766.

### CODE REVIEW

**Review by ice0 — APPROVED** [review]

**Comment by ice0** [comment]
Merged. Thank you!
