### ISSUE TITLE
1.4.0 fail to build with autotools

### ISSUE THREAD

**Issue by marillat** [synfig/synfig#1843]
synfig 1.4.0 Debian unstable amd64

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I../.. -I../../src -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -pthread -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/libxml++-2.6 -I/usr/lib/x86_64-linux-gnu/libxml++-2.6/include -I/usr/include/libxml2 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-7 -I/usr/include/ImageMagick-7 -I/usr/include/x86_64-linux-gnu//ImageMagick-7 -I/usr/include/ImageMagick-7 -I/usr/include/x86_64-linux-gnu//ImageMagick-7 -I/usr/include/ImageMagick-7 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -DGL_GLEXT_PROTOTYPES -pthread -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -D_REENTRANT -I/usr/include/mlt++ -I/usr/include/mlt -I/usr/include/ETL -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -DWITH_OPENGL -DSYNFIG_NO_DEPRECATED -DLOCALEDIR=\"/usr/share/locale\" -DLIBDIR=\"/usr/lib/x86_64-linux-gnu\" -DSYSCONFDIR=\"/etc/synfig\" -fdebug-prefix-map=/src/synfig-1.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -DNDEBUG -W -Wall -c rendering/renderer.cpp  -fPIC -DPIC -o rendering/.libs/libsynfig_la-renderer.o
In file included from rendering/opengl/task/taskgl.h:32,
                 from rendering/renderer.cpp:54:
rendering/opengl/task/../surfacegl.h:60:15: error: conflicting return type specified for 'virtual void synfig::rendering::SurfaceGL::reset_vfunc()'
   60 |  virtual void reset_vfunc();
      |               ^~~~~~~~~~~
In file included from rendering/task.h:39,
                 from rendering/optimizer.h:28,
                 from rendering/renderer.h:35,
                 from rendering/renderer.cpp:44:
rendering/surface.h:122:15: note: overridden function is 'virtual bool synfig::rendering::Surface::reset_vfunc()'
  122 |  virtual bool reset_vfunc()
      |               ^~~~~~~~~~~
In file included from rendering/renderer.cpp:54:
rendering/opengl/task/taskgl.h: In member function 'virtual synfig::rendering::Surface::Token::Handle synfig::rendering::TaskGL::get_mode_target_token() const':
rendering/opengl/task/taskgl.h:55:27: error: could not convert 'synfig::rendering::SurfaceGL::token' from 'synfig::rendering::Surface::Token' to 'synfig::rendering::Surface::Token::Handle' {aka 'synfig::ConstRef<synfig::rendering::Surface::Token>'}
   55 |   { return TargetSurface::token; }
      |                           ^~~~~
      |                           |
      |                           synfig::rendering::Surface::Token
make[3]: *** [Makefile:3510: rendering/libsynfig_la-renderer.lo] Error 1
```

**Comment by Keyikedalube** [comment]
Thanks for your contribution to Debian system.

Debian sid user here 😄 Excited for new stable release to roll out soon-ish 🏁

**Comment by rodolforg** [comment]
@marillat OpenGL rendering itself is broken, not only building with OpenGL support.

**Comment by rodolforg** [comment]
> Excited for new stable release to roll out soon-ish checkered_flag

And the new dev-release XD

**Comment by ice0** [comment]
@marillat by default OpenGL part should be disabled, did you enable it?

**Comment by marillat** [comment]
Yes, as this option was working in 1.2.2
Now synfig build fine without --with-opengl
Why an option who doesn't work is still here ?

**Comment by ice0** [comment]
Agree. I think we should disable it, until OpenGL is fixed.

**Comment by rodolforg** [comment]
This issue is already fixed in v1.4.1. It won't show OpenGL as a viable option for building
