### ISSUE TITLE
Fail to build with GCC 7.1.0

### ISSUE THREAD

**Issue by marillat** [synfig/synfig#396]
synfig 1.2.0
Debian unstable amd64
GCC 7.1.0
I think this bug is more related to etl (0.04.22 is installed)

````
/usr/include/ETL/_surface.h: In member function 'void etl::surface<T, AT, VP>::swap(const etl::surface<T, AT, VP>&)':
/usr/include/ETL/_surface.h:198:20: error: no matching function for call to 'swap(int&, const int&)'
   std::swap(w_,x.w_);

[...]

/usr/include/ETL/_surface.h:199:20: error: no matching function for call to 'swap(int&, const int&)'
   std::swap(h_,x.h_);

[...]

/usr/include/ETL/_surface.h:200:36: error: no matching function for call to 'swap(bool&, const bool&)'
   std::swap(deletable_,x.deletable_);
                                    ^
`````

**Comment by blackwarthog** [comment]
Please, attach full log of GCC

**Comment by marillat** [comment]
https://gist.github.com/marillat/29f2cdf1122c52d4198cca0e77423fc6

**Comment by morevnaproject** [comment]
@marillat Can you please try to build the latest master branch?

**Comment by marillat** [comment]
ETL from git, fail to build with the same error
https://gist.github.com/marillat/11b27e9914c1ec22dd13ce2604d830e9

**Comment by morevnaproject** [comment]
The fix is shipped with Synfig Studio 1.3.4 - https://morevnaproject.org/2017/08/10/synfig-studio-1-3-4-released/

**Comment by marillat** [comment]
The best is to wait for the next stable release or to package 1.3.4 ?

**Comment by morevnaproject** [comment]
We plan to ship 1.3.4 as next stable release (marked as 1.2.1). From code point of view they are expected to be 100% identical. It's hard to predict when 1.2.1 will be released, but most likely it will happen within a month.

**Comment by marillat** [comment]
Thanks. Then I'll wait for 1.2.1
