### PR TITLE
v1.5.2 release

### PR DESCRIPTION
**Pull request by ice0**
This is a minor update to the build.

Release notes:
- refactor: removed boost dependency (https://github.com/synfig/synfig/pull/2792)
- build: fixed includes for harfbuzz and fribidi libraries (https://github.com/synfig/synfig/pull/2442)
- build(mod_libavcodec): fixed build with FFMPEG 5.0 (https://github.com/synfig/synfig/pull/2734)
- build(autotools): patch for autoconf 2.72 h/t Frédéric Bérat (https://github.com/synfig/synfig/pull/2930)
- fix: mod_libavcodec didn't compile with MinGW (https://github.com/synfig/synfig/pull/2737)
- fix: Debian 9 building (https://github.com/synfig/synfig/pull/2517)

### CODE REVIEW

**Comment by rodolforg** [comment]
Is this just for testing purposes or planning to be an actual release?

We'll branch out from master?

**Comment by ice0** [comment]
> Is this just for testing purposes or planning to be an actual release?

I suggest to release this changes as 1.5.2 to fix this issue: https://github.com/synfig/synfig/issues/3382

**Comment by morevnaproject** [comment]
Hi! I've got the following error on building Linux packages  -
```
  CXX      libmod_libavcodec_la-main.lo
  CXX      libmod_libavcodec_la-trgt_av.lo
  CXX      libmod_libavcodec_la-mptr.lo
trgt_av.cpp: In member function 'bool Target_LibAVCodec::Internal::open(const String&, const synfig::RendDesc&)':
trgt_av.cpp:257:22: error: invalid conversion from 'const AVOutputFormat*' to 'AVOutputFormat*' [-fpermissive]
   context->oformat = format;
                      ^~~~~~
Makefile:602: recipe for target 'libmod_libavcodec_la-trgt_av.lo' failed
make[4]: *** [libmod_libavcodec_la-trgt_av.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/build/packet/linux-64/synfigcore-master/build/synfig/synfig-core/src/modules/mod_libavcodec'
Makefile:563: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/build/packet/linux-64/synfigcore-master/build/synfig/synfig-core/src/modules'
Makefile:466: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/build/packet/linux-64/synfigcore-master/build/synfig/synfig-core/src'
Makefile:688: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/build/packet/linux-64/synfigcore-master/build/synfig/synfig-core'
Makefile:556: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ice0** [comment]
> Hi! I've got the following error on building Linux packages

Should be fixed now.
